ConsommiTounsi/Models/Payment/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsommiTounsi.Models.Payment
{
    public class Cart
    {
        public int Id { get; set; }
        public int MyProperty { get; set; }
        public List<Item> Items { get; set; }
    }
}

ConsommiTounsi/Controllers/AdminController.cs
using ConsommiTounsi.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ConsommiTounsi.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            if (Session["user"] == null || ((User)Session["user"]).type != UserType.ADMIN)
                return RedirectToAction("Index", "Home");
            return View();
        }
    }
}

ConsommiTounsi/Controllers/CartController.cs
using ConsommiTounsi.Models.Payment;
using ConsommiTounsi.Models.User;
using ConsommiTounsi.Models.ViewModels;
using ConsommiTounsi.Repositories.Payment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ConsommiTounsi.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartRepository cartRepository;
        private readonly ICheckoutRepository checkoutRepository;

        public CartController(ICartRepository cartRepository, ICheckoutRepository checkoutRepository)
        {
            this.cartRepository = cartRepository;
            this.checkoutRepository = checkoutRepository;
        }

        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddItem(int id, int productId, int quantity)
        {
            var item = new Item()
            {
                Quantity = quantity
            };
            var model = await cartRepository.AddItem(id, item, productId);
            if (!string.IsNullOrWhiteSpace(model.ErrorMessage))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, model.ErrorMessage);
            }
            return Json(model);
        }

        public async Task<ActionResult> GetItems()
        {
            var user = Session["user"] as User;
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var response = await cartRepository.GetAsync((int)user.id);
            var items = response.Body.Items;

            return Json(items, JsonRequestBehavior.AllowGet);
        }


        public async Task<ActionResult> Details()
        {
            var user = Session["user"] as User;
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var response = await cartRepository.GetAsync((int)user.id);
            var cart = response.Body;
            if (cart == null || cart.Items.Count == 0)
            {
                return RedirectToAction("Index", "Product");
            }

            return View(cart);
        }

        [HttpPost]
        public async Task<ActionResult> RemoveItem(int id)
        {
            var model = await cartRepository.RemoveItem(id);
            if (!string.IsNullOrWhiteSpace(model.ErrorMessage))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, model.ErrorMessage);
            }
            return Json(model);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateItem(int id, int quantity)
        {
            var model = await cartRepository.UpdateItemQuantity(itemId: id, quantity);
            if (!string.IsNullOrWhiteSpace(model.ErrorMessage))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, model.ErrorMessage);
            }
            return Json(model);
        }

        public async Task<ActionResult> Checkout()
        {
            var user = Session["user"] as User;
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var response = await cartRepository.GetAsync((int)user.id);
            var cart = response.Body;
            if (cart == null || cart.Items.Count == 0)
            {
                return RedirectToAction("Index", "Product");
            }

            var model = new CheckoutViewModel()
            {
                Cart = cart,
            };

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Checkout(CheckoutViewModel model)
        {
            var user = Session["user"] as User;
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (model.Payment.PaymentType == PaymentType.ONLINE)
            {
                return RedirectToAction("OnlinePayment", "Payment");
            }

            var paymentModel = new PaymentModel
            {
                ShippingAddress = model.Payment.Address,
                PaymentType = model.Payment.PaymentType,
                UserId = (int)user.id
            };
            var response = await checkoutRepository.CreateAtDeliveryPayment(paymentModel);

            if (!response)
            {
                return View("~/Views/Shared/Error.cshtml");
            }

            return RedirectToAction("Index", "Home");
        }

        [ChildActionOnly]
        public ActionResult RenderCart()
        {
            var user = Session["user"] as User;
            if (user != null)
            {
                var response = cartRepository.Get((int)user.id);
                Cart cart = response.Body;
                return PartialView("_Cart", cart);
            }
            return PartialView("_Cart", null);
        }

        //private Cart _getCart()
        //{
        //    var user = Session["user"] as User;
        //    if (user != null)
        //    {
        //        return cartRepository.Get((int)user.id).Body;
        //    }
        //    return null;
        //}
    }
}

ConsommiTounsi/Controllers/ParticipationController.cs
using ConsommiTounsi.Models.Evenement;
using ConsommiTounsi.Models.User;
using ConsommiTounsi.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ConsommiTounsi.Controllers
{
    public class ParticipationController : Controller
    {
        // GET: Participation
        public ActionResult ParticipationsListAdmin()
        {
            HttpClient httpClient = HttpClientBuilder.Get(Session["api-cookie"]);
            HttpResponseMessage response = httpClient.GetAsync("Participations").Result;
            response.EnsureSuccessStatusCode();
            return View(response.Content.ReadAsAsync<IEnumerable<Participation>>().Result);
        }


 
        public ActionResult Participé(long EvId)
        {
            HttpClient httpClient = HttpClientBuilder.Get(Session["api-cookie"]);
            User user = (User)Session["user"];
            if (user == null)
            {
                return RedirectToAction("Login", "User");

            }
            else
            {
                long userId = user.id;
                string url = "Participation/" + userId + "/" + EvId;
                HttpResponseMessage response = httpClient.PostAsJsonAsync<Participation>(url, new Participation()).Result;
                response.EnsureSuccessStatusCode();
                return RedirectToAction("Index", "Evenement");
            }
        }

       

    }
}

ConsommiTounsi/Views/Shared/NotFound.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NotFound</title>
</head>
<body>
    <div>
        Resource not found 404 (fix this page)
    </div>
</body>
</html>

ConsommiTounsi/Views/Shared/_AdminLayout.cshtml
@{ var user = (ConsommiTounsi.Models.User.User)Session["user"]; }
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard - @ViewBag.Title</title>
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Shared/img/consommitounsi_icon.ico">
    @RenderSection("styles", required: true);
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    @Html.ActionLink("Dashboard", "Index", "Admin", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    @Html.ActionLink("Consommi tounsi #216", "Index", "Home", null, new { @class = "nav-link" })
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    @Html.ActionLink("Logout", "Logout", "User", new { @class = "nav-link" })
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                        <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>

                <!-- Messages Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-comments"></i>
                        <span class="badge badge-danger navbar-badge">3</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="~/Content/Dashboard/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Brad Diesel
                                        <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">Call me whenever you can...</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="~/Content/Dashboard/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        John Pierce
                                        <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">I got your message bro</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <!-- Message Start -->
                            <div class="media">
                                <img src="~/Content/Dashboard/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
                                <div class="media-body">
                                    <h3 class="dropdown-item-title">
                                        Nora Silvester
                                        <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                                    </h3>
                                    <p class="text-sm">The subject goes here</p>
                                    <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                                </div>
                            </div>
                            <!-- Message End -->
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
                    </div>
                </li>
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index", "Admin")" class="brand-link">
                <img src="~/Content/Shared/img/ConsommiTounsiLogo.png" alt="ConsommiTounsi Logo"
                     class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">ConsommiTounsi</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="info">
                        <a href="#" class="d-block">@user.username</a>
                    </div>
                </div>

                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item">
                            <a href="@Url.Action("ManageUsers", "User")" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Manage Users
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("ParticipationsListAdmin", "Participation")" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Participations
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("EventListAdmin", "Evenement")" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    Evenements
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("CagnotteListAdmin", "Cagnotte")" class="nav-link">
                                <i class="nav-icon fas fa-users"></i>
                                <p>
                                    cagnottes
                                </p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">@ViewBag.Title</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="@Url.Action("Index", "Admin")">Home</a></li>
                                <li class="breadcrumb-item active">@ViewBag.Title</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <strong>Copyright &copy; 2021 <a href="https://esprit.tn/">ESPRIT</a>.</strong>
            All rights reserved.
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    @RenderSection("scripts", required: true);
</body>
</html>

ConsommiTounsi/Views/Shared/_Cart.cshtml
@model ConsommiTounsi.Models.Payment.Cart
@{
    Layout = null;
    var items = Model.Items.ToList();
}





@if (Model != null)
{
    <li class="dropdown d-inline-block">
        <span class="dropdown-toggle" role="menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <a href="#">
                <span><svg width="35px" height="35px"><use xlink:href="#cart"></use></svg></span>
                <span class="text-danger d-lg-inline-block d-md-none d-sm-none d-none align-middle font-weight-bolder">
                </span><span class="text-danger price_cart d-md-inline-block align-middle font-weight-bolder">
                    @items.Count
                </span>
            </a>
        </span>
        @if (items != null && items.Count > 0)
        {
            <div class="dropdown-menu s_cart dropdown-menu-right">
                <ul class="shopping-cart p-2 ">
                    @foreach (var item in items)
                    {
                        <li class="pb-2 d-block">
                            <div class="media ">
                                <div>
                                    <a href="#">
                                        <img src="@item.Product.Picture"
                                             class="fst-image img-fluid rounded align-self-center" alt="@item.Product.Name">
                                    </a>
                                </div>
                                <div class="media-body">
                                    <h6 class="mt-0 f_15 text-right">
                                        @item.Product.Name
                                        @*<span class="float-right cart_cross">X</span>*@
                                    </h6>
                                    <p class="text-right"><span class="f_13">@item.Quantity x @item.Product.Price TND</span></p>
                                </div>
                            </div>
                        </li>
                    }
                    <li class="d-block text-muted font-weight-bolder p-2 border-bottom">
                        <span class="text-left">Subtotal</span>
                        <span class="float-right">@items.Sum(i => i.Product.Price * i.Quantity) TND</span>
                    </li>
                    <li class="d-block font-weight-bolder pt-2">
                        <span class="text-left">
                            @Html.ActionLink("Cart Details", "Details", "Cart", null,
                           new { style = "height: auto;" })
                        </span>
                        <span class="float-right">
                            @Html.ActionLink("Check Out", "Checkout", "Cart", null,
                           new { style = "height: auto;" })
                        </span>
                    </li>
                </ul>
            </div>
        }
    </li>
}

ConsommiTounsi/Views/Shared/_EnumName.cshtml
@model Enum

@if (EnumHelper.IsValidForEnumHelper(ViewData.ModelMetadata))
{
    string displayName = null;
    foreach (SelectListItem item in EnumHelper.GetSelectList(ViewData.ModelMetadata, (Enum)Model))
    {
        if (item.Selected)
        {
            displayName = item.Text ?? item.Value;
        }
    }

    if (String.IsNullOrEmpty(displayName))
    {
        if (Model == null)
        {
            displayName = String.Empty;
        }
        else
        {
            displayName = Model.ToString();
        }
    }

    @Html.DisplayTextFor(model => displayName)
}
else
{
    @Html.DisplayTextFor(model => model)
}